name: sequana_denovo
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python>=3.11
- bedtools
- blast
- bwa
- freebayes
- khmer
- graphviz
- multiqc
- sambamba
- samtools
- seqkit
- pip:
  - sequana
  - sequana_pipetools
